Update ImmortalWrt-openwrt_x86.yml

diff --git a/.github/workflows/ImmortalWrt-openwrt_x86.yml b/.github/workflows/ImmortalWrt-openwrt_x86.yml
--- a/.github/workflows/ImmortalWrt-openwrt_x86.yml
+++ b/.github/workflows/ImmortalWrt-openwrt_x86.yml
@@ -128,25 +128,54 @@ jobs:
       - name: Generate tools toolchain
         id: compile_tools_toolchain
         run: |
-          cd $GITHUB_WORKSPACE/openwrt
-          make tools/compile -j$(nproc)
-          make toolchain/compile -j$(nproc)    
+          cd openwrt
+          is_complie_error=0
+          if [[ "" == "true" ]]; then
+          if [[ "" == "true" ]]; then
+        echo "1 threads compile tools"
+        make tools/compile -j1 V=s
+        make toolchain/compile -j1 V=s
+        make package/cleanup -j1 V=s
+        make target/compile -j1 V=s
+        is_complie_error=${PIPESTATUS[0]}
+    else
+        echo "$(nproc) threads compile tools"
+        make tools/compile -j$(nproc) V=s
+        make toolchain/compile -j$(nproc) V=s
+        make package/cleanup -j$(nproc) V=s
+        make target/compile -j$(nproc) V=s
+        is_complie_error=${PIPESTATUS[0]}
+    fi
+  else
+    if [[ "" == "true" ]]; then
+        echo "1 threads compile tools"
+        make tools/compile -j1
+        make toolchain/compile -j1
+        make package/cleanup -j1
+        make target/compile -j1
+        is_complie_error=${PIPESTATUS[0]}
+    else
+        echo "$(nproc) threads compile tools"
+        make tools/compile -j$(nproc)
+        make toolchain/compile -j$(nproc)
+        make package/cleanup -j$(nproc)
+        make target/compile -j$(nproc)
+        is_complie_error=${PIPESTATUS[0]}
+    fi
+  fi
+  echo "complie result： $is_complie_error"
+  if [ "$is_complie_error" -eq 0 ]; then
+    echo "status=success" >> $GITHUB_OUTPUT
+  else
+    echo "status=failure" >> $GITHUB_OUTPUT
+    exit $is_complie_error
+  fi
+  df -hT    
 
       - name: Generate Frimware ruby
         id: compile_ruby
         run: |
-          cd $GITHUB_WORKSPACE/openwrt
-          make package/feeds/packages/ruby/{clean,compile} V=s
-
-          echo "----------------------------------------------------------------"
-          make package/feeds/packages/ruby/{clean,compile}
-          cd $GITHUB_WORKSPACE
-      - name: Generate Frimware
-        id: compile
-        run: |
-          cd openwrt
-
-          make package/feeds/packages/ruby/{clean,compile} V=s
+          
 
     - name: Check space usage
       if: (!cancelled())
@@ -157,7 +186,43 @@ jobs:
       if: steps.compile.outputs.status == 'success' && env.UPLOAD_BIN_DIR == 'true'
       with:
         name: OpenWrt_bin${{ env.DEVICE_NAME }}${{ env.FILE_DATE }}
-        path: openwrt/bin
+        path: openwrt/bincd openwrt
+  is_complie_error=0
+  
+  if [[ "" == "true" ]]; then
+    if [[ "" == "true" ]]; then
+        echo "1 threads compile frimware"
+        make -j1 V=s
+        is_complie_error=${PIPESTATUS[0]}
+    else
+        echo "$(nproc) threads compile frimware"
+        make -j$(nproc) V=s
+        is_complie_error=${PIPESTATUS[0]}
+    fi
+  else
+    if [[ "" == "true" ]]; then
+        echo "1 threads compile frimware"
+        make -j1
+        is_complie_error=${PIPESTATUS[0]}
+    else
+        echo "$(nproc) threads compile frimware"
+        make -j$(nproc)
+        is_complie_error=${PIPESTATUS[0]}
+    fi
+  fi
+  
+  
+  
+  
+  echo "complie result： $is_complie_error"
+  if [ "$is_complie_error" -eq 0 ]; then
+    echo "status=success" >> $GITHUB_OUTPUT
+  else
+    echo "status=failure" >> $GITHUB_OUTPUT
+    exit $is_complie_error
+  fi
+  
+  df -hT
 
     - name: Organize files
       id: organize
